"""Guided Speculative Inference (GSI) baseline — shared-component variant.

Mechanism (following the paper's structure, instantiated with this
project's shared components so comparisons are controlled):

  - a SMALL model proposes one reasoning step at a time (stop at a step
    delimiter);
  - a REWARD model scores the partial solution after each step (expected
    score over {1..5} tokens, design-A suffix form);
  - if the step's reward falls below --fallback-threshold, the step is
    regenerated by the TARGET model instead (threshold-triggered fallback);
  - each candidate accumulates log-weight = beta * sum(step rewards,
    normalized to [0,1]) + optional likelihood correction
    sum(log p_target(step) - log p_small(step)) for small-proposed steps;
  - soft best-of-n: final answer drawn from softmax over candidate weights
    (argmax also reported).

Controlled variant (same proposer/reward/target family as the SMC system);
NOT a paper-faithful reproduction (different reward model and step
conventions) — label accordingly in tables.
"""

import argparse
import math
import time


STEP_STOP = "\n\n"
MAX_STEP_TOKENS = 192
SUFFIX_FORM = (
    "\n\n[Self-assessment: on a scale of 1-5, the probability that this "
    "solution-in-progress reaches a fully correct final answer is: "
)


def expected_score(out, score_ids):
    mi = out.get("meta_info", {})
    top = mi.get("output_top_logprobs")
    if not top or not top[0]:
        return None
    p = {}
    for e in top[0]:
        lp, tid = e[0], e[1]
        if tid in score_ids:
            p[score_ids.index(tid) + 1] = math.exp(lp)
    if not p:
        return None
    z = sum(p.values())
    return sum(k * v for k, v in p.items()) / z


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--benchmark", choices=["gsm8k", "math500"], required=True)
    ap.add_argument("--target", required=True)
    ap.add_argument("--small", default="Qwen/Qwen3.5-4B")
    ap.add_argument("--reward", default="Qwen/Qwen3.8-27B")
    ap.add_argument("--num-questions", type=int, default=100)
    ap.add_argument("--n-candidates", type=int, default=8)
    ap.add_argument("--max-rounds", type=int, default=12)
    ap.add_argument("--fallback-threshold", type=float, default=2.5)
    ap.add_argument("--beta", type=float, default=2.0)
    ap.add_argument("--temperature", type=float, default=0.7)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--target-tp", type=int, default=1)
    ap.add_argument("--mem-fraction-target", type=float, default=0.85)
    ap.add_argument("--target-base-gpu", type=int, default=2)
    ap.add_argument("--mem-fraction-small", type=float, default=0.85)
    ap.add_argument("--small-base-gpu", type=int, default=0)
    ap.add_argument("--mem-fraction-reward", type=float, default=0.85)
    ap.add_argument("--reward-base-gpu", type=int, default=1)
    ap.add_argument("--disable-thinking", action="store_true")
    args = ap.parse_args()

    import sglang as sgl
    from transformers import AutoTokenizer

    if args.benchmark == "gsm8k":
        from accuracy_test_gsm8k import load_gsm8k as load, extract_answer
    else:
        from accuracy_test_math500 import (
            load_math500 as load, extract_boxed, normalize_answer)

        def extract_answer(t):
            return normalize_answer(extract_boxed(t))

    tok = AutoTokenizer.from_pretrained(args.target)
    prompts, labels = load(tok, args.num_questions,
                           disable_thinking=args.disable_thinking)

    rtok = AutoTokenizer.from_pretrained(args.reward)
    score_ids = [rtok.encode(str(d), add_special_tokens=False)[0]
                 for d in range(1, 6)]

    common = dict(trust_remote_code=True, attention_backend="triton",
                  random_seed=args.seed)
    small = sgl.Engine(model_path=args.small,
                       mem_fraction_static=args.mem_fraction_small,
                       max_running_requests=64,
                       max_mamba_cache_size=64,
                       base_gpu_id=args.small_base_gpu, **common)
    reward = sgl.Engine(model_path=args.reward,
                        mem_fraction_static=args.mem_fraction_reward,
                        max_running_requests=48,
                        max_mamba_cache_size=48,
                        base_gpu_id=args.reward_base_gpu, **common)
    tkw = dict(common)
    if args.target_tp > 1:
        tkw.update(tp_size=args.target_tp, disable_custom_all_reduce=True,
                   enforce_disable_flashinfer_allreduce_fusion=True)
    target = sgl.Engine(model_path=args.target,
                        mem_fraction_static=args.mem_fraction_target,
                        max_running_requests=32,
                        max_mamba_cache_size=32,
                        base_gpu_id=args.target_base_gpu, **tkw)

    n = args.n_candidates
    Q = len(prompts)
    texts = [["" for _ in range(n)] for _ in range(Q)]
    weights = [[0.0] * n for _ in range(Q)]
    done = [[False] * n for _ in range(Q)]
    fallbacks = 0
    small_steps = 0

    tic = time.perf_counter()
    for rnd in range(args.max_rounds):
        active = [(q, c) for q in range(Q) for c in range(n) if not done[q][c]]
        if not active:
            break
        sp = {"max_new_tokens": MAX_STEP_TOKENS,
              "temperature": args.temperature, "stop": STEP_STOP}
        outs = small.generate(
            [prompts[q] + texts[q][c] for q, c in active], sp)
        steps = [o["text"] for o in outs]
        # A candidate is complete when generation ended on EOS rather than
        # the step-delimiter stop string (answer-extraction alone is too
        # lenient a termination signal on GSM8K-style tasks).
        def _eos_done(o):
            fr = o.get("meta_info", {}).get("finish_reason") or {}
            return fr.get("type") == "stop" and fr.get("matched") != STEP_STOP
        finished = [_eos_done(o) for o in outs]
        small_steps += len(steps)
        souts = reward.generate(
            [prompts[q] + texts[q][c] + s + SUFFIX_FORM
             for (q, c), s in zip(active, steps)],
            {"max_new_tokens": 1, "temperature": 0.0},
            return_logprob=True, top_logprobs_num=20)
        rewards = [expected_score(o, score_ids) or 1.0 for o in souts]
        fb_idx = [i for i, r in enumerate(rewards)
                  if r < args.fallback_threshold]
        if fb_idx:
            fouts = target.generate(
                [prompts[active[i][0]] + texts[active[i][0]][active[i][1]]
                 for i in fb_idx], sp)
            fsouts = reward.generate(
                [prompts[active[i][0]] + texts[active[i][0]][active[i][1]]
                 + o["text"] + SUFFIX_FORM
                 for i, o in zip(fb_idx, fouts)],
                {"max_new_tokens": 1, "temperature": 0.0},
                return_logprob=True, top_logprobs_num=20)
            for i, o, so in zip(fb_idx, fouts, fsouts):
                steps[i] = o["text"]
                rewards[i] = expected_score(so, score_ids) or rewards[i]
                finished[i] = _eos_done(o)
                fallbacks += 1
        for (q, c), s, r, fin in zip(active, steps, rewards, finished):
            texts[q][c] += s + (STEP_STOP if not s.endswith(STEP_STOP) else "")
            weights[q][c] += args.beta * (r - 1) / 4.0
            if fin or len(texts[q][c]) > 6000:
                done[q][c] = True
    wall = time.perf_counter() - tic

    import random
    rng = random.Random(args.seed)
    soft = argm = 0
    for q in range(Q):
        cands = [(weights[q][c], extract_answer(texts[q][c]))
                 for c in range(n)]
        valid = [(w, a) for w, a in cands if a is not None]
        if not valid:
            continue
        argm += max(valid)[1] == labels[q]
        m = max(w for w, _ in valid)
        probs = [math.exp(w - m) for w, _ in valid]
        z = sum(probs)
        r = rng.random() * z
        acc = 0.0
        pick = valid[-1][1]
        for (w, a), p in zip(valid, probs):
            acc += p
            if r <= acc:
                pick = a
                break
        soft += pick == labels[q]
    print(f"GSI target={args.target} n={n} thr={args.fallback_threshold} "
          f"beta={args.beta}")
    print(f"  soft-BoN accuracy:  {soft}/{Q}")
    print(f"  argmax accuracy:    {argm}/{Q}")
    print(f"  small steps={small_steps} fallbacks={fallbacks} "
          f"wall={wall:.1f}s")
    for eng in (small, reward, target):
        eng.shutdown()


if __name__ == "__main__":
    import os
    import sys

    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    main()
